// curiosidades.js
module.exports = [
    "¿Sabías que las abejas nunca duermen?",
    "Los pulpos tienen tres corazones.",
    "El corazón de una ballena azul es tan grande como un coche.",
    "Un rayo puede calentar el aire alrededor de él a temperaturas cinco veces más calientes que la superficie del sol.",
    "Los tiburones han existido por más tiempo que los árboles.",
    "Un solo pie humano tiene 26 huesos.",
    "Los gatos tienen más huesos en sus cuerpos que los humanos.",
    "El ojo humano puede distinguir alrededor de 10 millones de colores diferentes.",
    "Los delfines tienen nombres para cada uno y se llaman entre sí.",
    "La lengua de una ballena azul puede pesar tanto como un elefante.",
    "Los caracoles pueden dormir hasta tres años.",
    "El cocodrilo no puede sacar la lengua.",
    "Las estrellas de mar no tienen cerebro.",
    "Un grupo de flamencos se llama 'belleza'.",
    "El tiburón más antiguo conocido tenía aproximadamente 400 años.",
    "Los camaleones pueden mover sus ojos en dos direcciones diferentes al mismo tiempo.",
    "Un día en Venus dura más que un año en Venus.",
    "Las mariposas tienen receptores de sabor en sus patas.",
    "Los murciélagos siempre giran a la izquierda al salir de una cueva.",
    "Un koala puede dormir hasta 22 horas al día.",
    "El animal más rápido del mundo es el halcón peregrino.",
    "Los pingüinos tienen glándulas especiales para filtrar la sal del agua que beben.",
    "El cerebro humano es más activo durante la noche que durante el día.",
    "El único mamífero capaz de volar es el murciélago.",
    "Las cebras son negras con rayas blancas.",
    "Las hormigas no duermen y no tienen pulmones.",
    "El tiburón martillo tiene un campo de visión de 360 grados.",
    "Los caballitos de mar son los únicos animales en los que el macho da a luz.",
    "Las ranas pueden respirar a través de su piel.",
    "Las jirafas tienen la misma cantidad de vértebras en el cuello que los humanos.",
    "Los elefantes son los únicos animales que no pueden saltar.",
    "El corazón de un camarón está en su cabeza.",
    "Las avestruces pueden correr más rápido que los caballos.",
    "El pez payaso es hermafrodita y puede cambiar de sexo.",
    "La medusa Turritopsis dohrnii es conocida como la medusa inmortal porque puede revertir su proceso de envejecimiento.",
    "El colibrí es el único pájaro que puede volar hacia atrás.",
    "El aliento de un perro de pradera es capaz de detener su propio crecimiento cuando detecta la presencia de depredadores.",
    "Los caracoles pueden sobrevivir sin comida durante varios meses.",
    "Las arañas pueden regenerar sus patas si las pierden.",
    "El ornitorrinco es uno de los pocos mamíferos que ponen huevos.",
    "Los dragones de Komodo tienen un veneno mortal en su saliva.",
    "El axolote es capaz de regenerar partes de su cuerpo, incluyendo su corazón y su cerebro.",
    "El cerebro de un avestruz es más pequeño que su ojo.",
    "Las estrellas de mar pueden regenerar sus brazos perdidos.",
    "El sol representa el 99.86% de la masa del sistema solar.",
    "La superficie de Marte es comparable a la superficie de la Tierra en términos de área.",
    "La Gran Muralla China no es visible desde el espacio a simple vista.",
    "La sangre de los pulpos es azul debido a una molécula llamada hemocianina.",
    "Los pingüinos tienen una glándula cerca de sus ojos que filtra el exceso de sal del agua que beben.",
    "El corazón de un colibrí late hasta 1.200 veces por minuto.",
    "Las medusas están formadas en un 95% por agua.",
    "Los tiburones pueden detectar una gota de sangre en 100 litros de agua.",
    "Las vacas tienen amigos y se estresan cuando están separados de ellos.",
    "Los koalas tienen huellas dactilares que son casi indistinguibles de las de los humanos.",
    "El pez gato tiene un órgano especializado que le permite detectar vibraciones en el agua.",
    "La Luna se aleja de la Tierra a una velocidad de aproximadamente 3.8 centímetros por año.",
    "Los lagartos pueden regenerar su cola si la pierden.",
    "La Tierra es el único planeta conocido con agua en estado líquido en su superficie.",
    "Las ballenas jorobadas tienen canciones complejas que pueden durar hasta 20 minutos.",
    "La Torre Eiffel puede ser hasta 15 cm más alta durante el verano debido a la expansión térmica.",
    "Los elefantes tienen un órgano especial en su trompa que les permite sentir vibraciones en el suelo.",
    "El ojo de un avestruz es más grande que su cerebro.",
    "La mayor parte de la energía del sol llega a la Tierra en forma de luz visible.",
    "El agua compone alrededor del 70% de la superficie terrestre.",
    "Las ranas pueden ver a través de sus párpados, ya que tienen una membrana transparente que les permite ver.",
    "El ADN humano es aproximadamente un 99.9% idéntico entre todas las personas.",
    "La mayoría de las arañas tienen ocho ojos, aunque algunas tienen seis o incluso dos.",
    "Las ballenas azules pueden alcanzar longitudes de hasta 30 metros y pesar hasta 200 toneladas.",
    "Los flamencos obtienen su color rosado de los pigmentos en su dieta, como los carotenoides.",
    "Las vacas tienen amigos y se estresan cuando están separados de ellos.",
    "El zorro ártico cambia el color de su pelaje para adaptarse a las estaciones del año.",
    "La velocidad de la luz es de aproximadamente 300.000 kilómetros por segundo.",
    "El sol es una estrella de tipo G2V, lo que significa que es una estrella enana amarilla.",
    "El mayor desierto del mundo no es el Sahara, sino la Antártida, debido a su baja precipitación.",
    "Las tortugas pueden vivir tanto en el agua como en tierra y tienen una longevidad excepcional.",
    "El caracol de tierra puede dormir hasta tres años durante condiciones adversas.",
    "Las ratas tienen una excelente memoria espacial y pueden recordar rutas durante largos períodos.",
    "El ser humano promedio tiene entre 5 y 6 litros de sangre en su cuerpo.",
    "La temperatura más alta registrada en la Tierra fue de 56.7°C en Furnace Creek Ranch, California, en 1913.",
    "Los pulpos tienen tres corazones.",
    "El corazón de una ballena azul es tan grande como un coche.",
    "Un rayo puede calentar el aire alrededor de él a temperaturas cinco veces más calientes que la superficie del sol.",
    "Los tiburones han existido por más tiempo que los árboles.",
    "Un solo pie humano tiene 26 huesos.",
    "Los gatos tienen más huesos en sus cuerpos que los humanos.",
    "El ojo humano puede distinguir alrededor de 10 millones de colores diferentes.",
    "Los delfines tienen nombres para cada uno y se llaman entre sí.",
    "Las ranas de cristal tienen una piel tan delgada que puedes ver sus órganos internos a través de ella.",
    "Los kiwis tienen un sentido del olfato extremadamente agudo y fosas nasales en la punta del pico.",
    "Los pulgas de agua pueden saltar hasta 200 veces su longitud en un solo salto.",
    "El pez luna o Mola Mola puede llegar a pesar más de 2,000 kg.",
    "Los camaleones cambian de color no solo para camuflarse, sino también para regular su temperatura y comunicarse.",
    "Los pandas gigantes tienen un sexto dedo en sus patas que les ayuda a agarrar bambú.",
    "Las mariposas monarca migran hasta 4,800 km desde América del Norte hasta México.",
    "Los pececillos de plata pueden sobrevivir sin agua durante largos períodos al entrar en un estado de letargo.",
    "El tiburón ballena es el pez más grande del océano y se alimenta principalmente de plancton y pequeños peces.",
    "Los lobos tienen un sistema de comunicación complejo que incluye vocalizaciones, lenguaje corporal y marcas de olor.",
    "Las pirámides de Egipto fueron originalmente cubiertas con una capa de piedra caliza pulida que brillaba bajo el sol.",
    "El punto más bajo de la Tierra es la Fosa de las Marianas, que se encuentra a más de 11,000 metros bajo el nivel del mar.",
    "Los árboles más antiguos del mundo son los pinos de Bristlecone en California, que tienen más de 5,000 años.",
    "El sol representa el 99.86% de la masa del sistema solar.",
    "Los antiguos romanos usaban orina para blanquear la ropa debido a su contenido de amoníaco.",
    "La Torre Eiffel puede ser 15 cm más alta durante el verano debido a la expansión térmica del metal.",
    "La distancia entre la Tierra y la Luna es de aproximadamente 384,400 km.",
    "En el espacio, los astronautas pueden llegar a crecer hasta 5 cm más largos debido a la falta de gravedad.",
    "El cerebro humano está compuesto en un 75% de agua.",
    "Los tiburones tienen una visión excelente y pueden detectar la presencia de una gota de sangre en 100 litros de agua.",
    "La miel es el único alimento que no se echa a perder; se han encontrado frascos de miel en tumbas egipcias que aún eran comestibles después de miles de años."
];
